package com.wasseemb.featherforreddit.SubredditJSON;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.util.List;

public class Data_ {

  @SerializedName("contest_mode") @Expose public Boolean contestMode;
  @SerializedName("subreddit_name_prefixed") @Expose public String subredditNamePrefixed;
  @SerializedName("banned_by") @Expose public Object bannedBy;
  @SerializedName("media_embed") @Expose public MediaEmbed mediaEmbed;
  @SerializedName("thumbnail_width") @Expose public Object thumbnailWidth;
  @SerializedName("subreddit") @Expose public String subreddit;
  @SerializedName("selftext_html") @Expose public Object selftextHtml;
  @SerializedName("selftext") @Expose public String selftext;
  @SerializedName("likes") @Expose public Object likes;
  @SerializedName("suggested_sort") @Expose public Object suggestedSort;
  @SerializedName("user_reports") @Expose public List<Object> userReports = null;
  @SerializedName("secure_media") @Expose public Object secureMedia;
  @SerializedName("link_flair_text") @Expose public String linkFlairText;
  @SerializedName("id") @Expose public String id;
  @SerializedName("view_count") @Expose public Object viewCount;
  @SerializedName("secure_media_embed") @Expose public SecureMediaEmbed secureMediaEmbed;
  @SerializedName("clicked") @Expose public Boolean clicked;
  @SerializedName("report_reasons") @Expose public Object reportReasons;
  @SerializedName("author") @Expose public String author;
  @SerializedName("saved") @Expose public Boolean saved;
  @SerializedName("mod_reports") @Expose public List<Object> modReports = null;
  @SerializedName("name") @Expose public String name;
  @SerializedName("score") @Expose public Integer score;
  @SerializedName("approved_by") @Expose public Object approvedBy;
  @SerializedName("over_18") @Expose public Boolean over18;
  @SerializedName("domain") @Expose public String domain;
  @SerializedName("hidden") @Expose public Boolean hidden;
  @SerializedName("thumbnail") @Expose public String thumbnail;
  @SerializedName("subreddit_id") @Expose public String subredditId;
  @SerializedName("edited") public Boolean edited;
  @SerializedName("link_flair_css_class") @Expose public String linkFlairCssClass;
  @SerializedName("author_flair_css_class") @Expose public String authorFlairCssClass;
  @SerializedName("gilded") @Expose public Integer gilded;
  @SerializedName("downs") @Expose public Integer downs;
  @SerializedName("brand_safe") @Expose public Boolean brandSafe;
  @SerializedName("archived") @Expose public Boolean archived;
  @SerializedName("removal_reason") @Expose public Object removalReason;
  @SerializedName("can_gild") @Expose public Boolean canGild;
  @SerializedName("thumbnail_height") @Expose public Object thumbnailHeight;
  @SerializedName("hide_score") @Expose public Boolean hideScore;
  @SerializedName("spoiler") @Expose public Boolean spoiler;
  @SerializedName("permalink") @Expose public String permalink;
  @SerializedName("num_reports") @Expose public Object numReports;
  @SerializedName("locked") @Expose public Boolean locked;
  @SerializedName("stickied") @Expose public Boolean stickied;
  @SerializedName("created") @Expose public Double created;
  @SerializedName("url") @Expose public String url;
  @SerializedName("author_flair_text") @Expose public String authorFlairText;
  @SerializedName("quarantine") @Expose public Boolean quarantine;
  @SerializedName("title") @Expose public String title;
  @SerializedName("created_utc") @Expose public Double createdUtc;
  @SerializedName("distinguished") @Expose public Object distinguished;
  @SerializedName("media") @Expose public Object media;
  @SerializedName("num_comments") @Expose public Integer numComments;
  @SerializedName("is_self") @Expose public Boolean isSelf;
  @SerializedName("visited") @Expose public Boolean visited;
  @SerializedName("subreddit_type") @Expose public String subredditType;
  @SerializedName("is_video") @Expose public Boolean isVideo;
  @SerializedName("ups") @Expose public Integer ups;
  @SerializedName("preview") @Expose public Preview preview;
  @SerializedName("post_hint") @Expose public String postHint;
}
